### PR TITLE
frontend: sortable tables

### PR DESCRIPTION
**Pull request by klarasm**
Just putting this up here, this is something I use. If there's anyone else interested I'm willing to try and clean this up but I don't really know javascript and someone else could probably do a better job. Can be seen live on https://lg.kasm.eu/

Adapted from https://stackoverflow.com/a/57080195.

### CODE REVIEW

**Comment by xddxdd** [comment]
Thanks for your contribution, looks great!

One suggestion: can you add "Name" as the secondary sorting criteria? Personally, I prefer that if I'm sorting by State, the items with the same state are still sorted by their names.

**Comment by klarasm** [comment]
Something like this?
It would be nice if it was a bit more flexible, though. For example, if sorted by "Since" first and then by "State" it could use "Since" as the secondary criteria instead but I haven't been able to get that work yet.

**Comment by xddxdd** [comment]
Yes, this looks good. I don't think we need that flexibility though.

I believe the common use case is to categorize peerings by protocol (or state), and sorting by multiple columns isn't that necessary. Plus, if the order matters, the user may be confused with the behavior.

Please mark your PR as non-draft if you feel it's ready, so I can merge it. One last suggestion though - please move `sortTable.js` into `static` folder, as that's where all JS files live in.

**Comment by klarasm** [comment]
I've cleaned it up and moved `sortTable.js` into `static`.
I agree about that the order mattering could be confusing, the current behavior is probably good enough.

**Pull request merged**
